import { NodeData, AddLinkData } from './types';

export const nodeData: NodeData[] = [
  { label: "CIRION_3G", row: 1},
  { label: "", row: 1, size: [0, 0] },
  { label: "CIRION_7G", row: 1},
  { label: "", row: 1, size: [0, 0] },
  { label: "", row: 1, size: [0, 0] },
  { label: "SFP1", row: 2},
  { label: "SFP2", row: 2},
  { label: "SFP3", row: 2},
  { label: "SFP4", row: 2},
  { label: "SFP5", row: 2},
  { label: "SFP6", row: 2},
  { label: "SFP7", row: 2},
  { label: "SFP8", row: 2},
  { label: "SFP9", row: 2},
  { label: "SFP10", row: 2},
  { label: "SFP11", row: 2},
  { label: "SFP12", row: 2},
  { label: "SFP13", row: 2},
  { label: "SFP14", row: 2},
  { label: "SFP15", row: 2},
  { label: "SFP16", row: 2},
  { label: "", row: 3, size: [0, 0] },
  { label: "LIBERTADOR", row: 3},
  { label: "", row: 3, size: [0, 0] },
  { label: "", row: 3, size: [0, 0] },
  { label: "OLT_1", row: 3},
  { label: "OLT_2", row: 3},
  { label: "OLT_3", row: 3},
  { label: "OLT_4", row: 3},
  { label: "", row: 3, size: [0, 0] },
  { label: "911_1", row: 3},
  { label: "911_2", row: 3},
  { label: "", row: 3, size: [0, 0] },
  { label: "", row: 3, size: [0, 0] },
  { label: "", row: 4, size: [0, 0] },
  { label: "", row: 4, size: [0, 0] },
  { label: "DATA_CENTER_911", row: 4 }
];

export const addLinks: AddLinkData[] = [
  {
    from: "CIRION_3G",
    to: "SFP1",
    speed: "3 gb",
    label: "3 gb",
  },
  {
    from: "CIRION_7G",
    to: "SFP11",
    speed: "7 gb",
    label: "7 gb",
  },
  {
    from: "SFP1",
    to: "SFP16",
    speed: "1.90 gb",
    label: "buss",
  },
  {
    from: "SFP2",
    to: "LIBERTADOR",
    speed: "486 mb",
    label: "ARSAT-1",
  },
  {
    from: "SFP4",
    to: "LIBERTADOR",
    speed: "586 mb",
    label: "ARSAT-2",
  },
  {
    from: "SFP6",
    to: "OLT_1",
    speed: "350 mb",
    label: "350 mb",
  },
  {
    from: "SFP8",
    to: "OLT_2",
    speed: "287 Mb",
    label: "287 Mb",
  },
  {
    from: "SFP9",
    to: "OLT_3",
    speed: "287 Mb",
    label: "287 Mb",
  },
  {
    from: "SFP10",
    to: "OLT_4",
    speed: "287 Mb",
    label: "287 Mb",
  },
  {
    from: "SFP13",
    to: "911_1",
    speed: "287 Mb",
    label: "287 Mb",
  },
  {
    from: "SFP14",
    to: "911_2",
    speed: "287 Mb",
    label: "287 Mb",
  },
  {
    from: "911_1",
    to: "DATA_CENTER_911",
    speed: "728 Mb",
    label: "728 Mb",
  },
  {
    from: "911_2",
    to: "DATA_CENTER_911",
    speed: "485 Mb",
    label: "485 Mb",
  },
];